# Site
repository: limchiawei9539/modern-resume-theme
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Lim Chia Wei
title: Software Engineer
email: admin@mikelim.dev
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: resume.mikelim.dev
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username:  limchiawei9539
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: lim-chia-wei
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "G-9CLC80DJX7"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/mike.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced Software Engineer with a demonstrated history of working in the machinery industry. 
  Skilled in SECS/GEM, English, JavaScript, C#, and Server Administration. Strong engineering professional 
  with a Bachelor's degree focused in Communication and Networking from Universiti Tunku Abdul Rahman (UTAR). 

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: EasyParcel
        sub_title: Web Developer Trainee
        caption: September 2018 - December 2018 
        link: www.easyparcel.my
        #description: | # this will include new lines to allow paragraphs
        #  Description of role
      - layout: right
        title: NSW Automation
        sub_title: Software Engineer
        caption: February 2020 - January 2022 
        link: www.nswautomation.com
        #description: | # this will include new lines to allow paragraphs
        #  Description of role
      - layout: right
        title: Thunder Software Technology Malaysia
        sub_title: Software Engineer
        caption: January 2022 - August 2022
        link: www.thundersoft.com
        #description: | # this will include new lines to allow paragraphs
        #  Description of role
      - layout: right
        title: Intel Corporation
        sub_title: FPGA Development Tool Engineer
        caption: August 2022 - Present
        link: www.intel.com
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: TARUC Penang
        sub_title: Diploma in Science(Internet Technology)
        caption: 2014 - 2016
      - layout: top-right
        title: UTAR Kampar
        sub_title: Bachelor in Information Technology (Communications and Networking)
        caption: 2017 - 2020

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
